### ISSUE TITLE
Any working examples? Or screenshot of success runs?

### ISSUE THREAD

**Issue by HudsonHuang** [kourgeorge/origin#6]
Hi, It's nice work! But I think it might be more lively and interesting if you add some examples to the readme document.

**Comment by kourgeorge** [comment]
I Agree, the visualization needs much work to do. I built a simpler dashboard based on heat maps to show where the creatures are and food are located as well as some statistics of the actions, population age, etc... 

![image](https://user-images.githubusercontent.com/12570182/91538174-180dbc00-e920-11ea-9ecb-43121dcb17cd.png)
